/** Design tokens copied verbatim from the Stitch "Canada Immigration Toolkit"
 *  design system (projects/9957550555126415088). Do not substitute defaults. */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#858383',
        'primary-fixed': '#e5e2e1',
        'on-primary-fixed': '#1c1b1b',
        'surface-dim': '#dadada',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f0f1f1',
        'surface-tint': '#5f5e5e',
        'inverse-primary': '#c9c6c5',
        'secondary-fixed-dim': '#c7c6c6',
        'on-tertiary-fixed-variant': '#464747',
        'secondary-fixed': '#e3e2e2',
        'on-tertiary-container': '#838484',
        'on-secondary': '#ffffff',
        'surface-container': '#eeeeee',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        'primary-fixed-dim': '#c9c6c5',
        'on-surface': '#1a1c1c',
        'on-secondary-container': '#646464',
        'tertiary-container': '#1a1c1c',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-container-low': '#f3f3f3',
        'on-secondary-fixed': '#1b1c1c',
        'on-tertiary': '#ffffff',
        tertiary: '#000000',
        'secondary-container': '#e3e2e2',
        'on-primary-fixed-variant': '#474646',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'outline-variant': '#c4c7c7',
        'on-error-container': '#93000a',
        primary: '#000000',
        surface: '#f9f9f9',
        'surface-bright': '#f9f9f9',
        'primary-container': '#1c1b1b',
        'on-secondary-fixed-variant': '#464747',
        secondary: '#5e5e5e',
        outline: '#747878',
        'surface-container-highest': '#e2e2e2',
        'tertiary-fixed': '#e3e2e2',
        'tertiary-fixed-dim': '#c7c6c6',
        'on-surface-variant': '#444748',
        'surface-container-high': '#e8e8e8',
        'surface-variant': '#e2e2e2',
        'inverse-surface': '#2f3131',
        // chart-specific tertiary tone used as the lightest data series
        'chart-baseline': '#d4d4d4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        sidebar_width: '260px',
        stack_sm: '8px',
        gutter: '24px',
        stack_md: '16px',
        container_padding: '32px',
        stack_lg: '32px',
        header_height: '64px',
      },
      fontFamily: {
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'data-mono': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '500' }],
        caption: ['11px', { lineHeight: '14px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
